# Generated by Django 3.0.6 on 2020-05-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapi', '0002_auto_20200505_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprofile',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
