# Generated by Django 3.0.6 on 2020-05-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapi', '0003_auto_20200505_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
